### ISSUE TITLE
GCD 里 block 不会循环引用

### ISSUE THREAD

**Issue by hssdx** [ChenYilong/iOSInterviewQuestions#100]
__weak __typeof__(self) weakSelf = self;
dispatch_group_async(_operationsGroup, _operationsQueue, ^
{
__typeof__(self) strongSelf = weakSelf;
[strongSelf doSomething];
[strongSelf doSomethingElse];
} );

这个例子不会循环引用，亲测，queue 在回调完 block 后会将 blokc 置空/移除

**Comment by 0x11901** [comment]
大哥，strong-weak dance了解一下，而且现在已经不用这么写了，Apple有编译器优化了。

**Comment by hssdx** [comment]
@0x11901 大哥，这不是我的代码，从原文粘贴出来的，你大概没看懂问题说的是什么吧？

**Comment by 0x11901** [comment]
是的，这下我懂了，这个方法是为了避免循环引用而这么做的。依文中的上下文环境改成循环引用的例子是要好一点

**Comment by fanxiushan** [comment]
确实，不用 weak dance 确实不会循环引用。这个和 YYKit 里的一个 Issue 很像，YY 当时的理解是错的。

**Comment by ZuhanLin** [comment]
我觉得作者想表达的意思是，系统级别API使用的block，如果在使用姿势上有构成互相应用，就可能产生循环引用，具体还要看编译器版本，因为我们之前担忧的很多可能构成循环引用的案例，在编译器迭代的过程中，已经得到了很好的优化。作为开发者只需要关心上层调用就可以了。
