### ISSUE TITLE
38.在block内如何修改block外部变量？

### ISSUE THREAD

**Issue by maxfong** [ChenYilong/iOSInterviewQuestions#11]
代码应该是
```
__block int a = 0;
void  (^foo)(void) = ^{ 
    a = 1; 
}
foo(); //这里，a的值被修改为1
```
吧？还是太高端，我看错了。。。

**Comment by ChenYilong** [comment]
多谢提醒，由于粗心写错了，已经[更正](https://github.com/ChenYilong/iOSInterviewQuestions/commit/598a6731674ac4287594e51f353312b7c8eab8bc)。
