### ISSUE TITLE
34题-36题-题目中很多对AutoreleasePool的理解都是有问题的

### ISSUE THREAD

**Issue by SepCode** [ChenYilong/iOSInterviewQuestions#112]
非自己创建并且ARC未优化成功的或__autoreleasing修饰的非Tagged Pointer对象。我这个总结也不全面，有时间写篇文章再放出新的总结

**Comment by ChenYilong** [comment]
厉害了，有相关的文章输出吗？我看看，也可以加我微信chenyilong1010，详细探讨下。

**Comment by SepCode** [comment]
首先36题中的描述不正确，AutoreleasePool是以AutoreleasePoolPage为结点的双向链表来实现的。

**Comment by SepCode** [comment]
34题中描述也不严谨，__autoreleasing修饰的autorelease对象，是在创建好之后调用objc_autorelease加入到释放池，并不是出了作用域。

**Comment by SepCode** [comment]
不过很多技术有时效性，没使用Tagged Pointer对象之前是另一个结果，没优化之前又是另一个结果。我也就仔细测试了一下这个，其他方面还需要大佬多多指教。

**Comment by SepCode** [comment]
@ChenYilong

**Comment by ChenYilong** [comment]
你加我微信没，我的id是：chenyilong1010，加后细聊。

**Comment by SepCode** [comment]
最近重新总结了自动释放池：
- autoreleasepool(不讨论Tagged Pointer对象)
    - 编译器会检查方法名是否以alloc/new/copy/mutableCopy开始，如果不是则自动将返回值的对象注册到autoreleasepool
        - objc_autoreleaseReturnValue被调用后紧接着调用objc_retainAutoreleasedReturnValue返回的对象不会注册到autoreleasepool中，而是直接传递到调用方。
    - 附有__weak修饰符的变量，访问的是注册到autoreleasepool的对象(MRC)
        - 在MRC下使用__weak修饰的变量时，会调用objc_loadWeak，它会调用objc_autorelease加入自动释放池。
        - 在ARC环境下会调用objc_loadWeakRetained和objc_release不会加入释放池。
    - id的指针(id *)或对象的指针(NSObject **)在没有显式指定时会被附加上__autoreleasing修饰符
    - 将对象赋值给附有__autoreleasing修饰符的变量，对象会被注册到autoreleasepool中
