### ISSUE TITLE
第一题风格纠错

### ISSUE THREAD

**Issue by KevinHM** [ChenYilong/iOSInterviewQuestions#12]
举个栗子：

```
@property (nonatomic, readonly, getter=isEditable, assign) BOOL editable;
```

有个非常细节的地方还要注意，property 的权限控制符的从左到右的顺序问题，从人体工程学角度考虑，从左到右应该推荐栗子中这么排列，[<<禅与Objective-C编程艺术 >> ](https://github.com/oa414/objc-zen-book-cn#%E5%B1%9E%E6%80%A7%E5%AE%9A%E4%B9%89)这里也有比较详细的解释。。。

**Comment by ChenYilong** [comment]
多谢提醒，[已经修复](https://github.com/ChenYilong/iOSInterviewQuestions/commit/be8b093906049e21a1763a321cd9a8202dd9452d)，你再帮忙看看还有其它的错误没有。
