### ISSUE TITLE
46 可以改进一下

### ISSUE THREAD

**Issue by pinxue** [ChenYilong/iOSInterviewQuestions#16]
+automaticallyNotifiesObserversForKey:

**Comment by ChenYilong** [comment]
能否详细讲下改进方案？如果您有时间也欢迎提一个 PR。费心了！

**Comment by pinxue** [comment]
我看你提到会触发两次，这个其实文档里有说明，主要就是这个 +automaticallyNotifiesObserversForKey: 类方法了。

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/KeyValueObserving/Articles/KVOCompliance.html#//apple_ref/doc/uid/20002178-SW3

**Comment by ChenYilong** [comment]
多谢补充, 已经在正文中添加说明.
