### ISSUE TITLE
发现了一个小错误

### ISSUE THREAD

**Issue by ianisme** [ChenYilong/iOSInterviewQuestions#17]
9. @property中有哪些属性关键字？/ @property 后面可以有哪些修饰符？中的第2个 读/写权限---readwrite(读写)、readooly (只读)

readonly写错了。。。

**Comment by ChenYilong** [comment]
多谢纠正，已经 [《修改》](https://github.com/ChenYilong/iOSInterviewQuestions/commit/277911cbc93f55ea97a1e6d827ac83d7ee76fd0b) ，还有其他的地方吗？我也一并改下！
