### ISSUE TITLE
请照顾下强迫症

### ISSUE THREAD

**Issue by XueSeason** [ChenYilong/iOSInterviewQuestions#18]
`同时实现NSCopyiog与NSMutableCopying协议`

这段文字中单词有误。

**Comment by ChenYilong** [comment]
非常感谢您的细心！！已经 [《修复》](https://github.com/ChenYilong/iOSInterviewQuestions/commit/c78f482026cf3b375ffa71779e1a1034901340fe) 了，您再看看还有其他的错误没有！
