### ISSUE TITLE
关于23点问题。

### ISSUE THREAD

**Issue by wuhanness** [ChenYilong/iOSInterviewQuestions#2]
23. 使用runtime Associate方法关联的对象，需要在主对象dealloc的时候释放么？
在ARC下不需要
在MRC中,对于使用retain或copy策略的需要

MRC下，如果A 关联了B 对象，保证在objc_setAssociatedObject后B对象只有A持有，即B.retainCount = 1的情况下，释放A对象，关联的B对象应该会释放吧。

**Comment by ChenYilong** [comment]
恩，是，我已将错误答案[更正](https://github.com/ChenYilong/iOSInterviewQuestions/commit/a57374d106e939b3f84ef9744659bf33f2df207c)

**Comment by wuhanness** [comment]
nice 啊。
