### ISSUE TITLE
第五个问题set方法的问题

### ISSUE THREAD

**Issue by skx926** [ChenYilong/iOSInterviewQuestions#4]
-(void)setSpeed:(int)_speed{
    if(_speed < 0) _speed = 0;
    if(_speed > 300) _speed = 300;
    _speed = speed;
}
上面这个是写错了吧，下面这样才对：

-(void)setSpeed:(int)speed{
    if(speed < 0) speed = 0;
    if(speed > 300) speed = 300;
    _speed = speed;
}

**Comment by ChenYilong** [comment]
已经[修正](https://github.com/ChenYilong/iOSInterviewQuestions/commit/9a3fd4dd4d7f27cdd645806a3441ff66e900a100)。
