### ISSUE TITLE
38题__block 内存堆栈问题

### ISSUE THREAD

**Issue by zhnnnnn** [ChenYilong/iOSInterviewQuestions#44]
```
 int a = 0;
NSLog(@"定义前：%p", &a);      
void (^foo)(void) = ^{
    NSLog(@"block内部：%p", &a);   
};
NSLog(@"定义后：%p", &a);     
foo();
```

我按照你的思路，a没加__block 修饰，打印结果按照你判断堆栈的思路，这时候block里面的a也是在堆区，block外面的都是在栈区。那么按道理这里的a值也应该是可以改的啊，毕竟改的是堆区内存。。。

**Comment by waterfly** [comment]
打印的结果显示，block内确实拷贝了a的地址。感觉是对没有__block的变量限制只读了

**Comment by JunyiXie** [comment]
看看我的回答就好了 https://github.com/ChenYilong/iOSInterviewQuestions/issues/69
跟 存哪的关系不是很大 呵呵
