### ISSUE TITLE
第39题

### ISSUE THREAD

**Issue by walkdianzi** [ChenYilong/iOSInterviewQuestions#61]
//我测试了以下，这种方式也会产生循环引用
[[NSNotificationCenter defaultCenter] addObserverForName:@"someNotification" 
                                                  object:nil 
                           queue:[NSOperationQueue mainQueue]
                                              usingBlock:^(NSNotification \* notification) {
                                                    self.someProperty = xyz; }]; 

//这种方式是不会产生循环引用的
dispatch_group_async(_operationsGroup, _operationsQueue, ^
{
        [self doSomething];
        [self doSomethingElse];
} );

**Comment by songgeb** [comment]
@ChenYilong 怎么还不更正？

**Comment by ChenYilong** [comment]
已经更正,谢谢指正.
