### ISSUE TITLE
第41提有点疑问

### ISSUE THREAD

**Issue by zziazm** [ChenYilong/iOSInterviewQuestions#63]
```
 dispatch_queue_t queue = dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0);
 dispatch_group_t group = dispatch_group_create();
 dispatch_group_async(group, queue, ^{[[SDWebImageDownloader sharedDownloader ] downloadImageWithURL:[NSURL URLWithString:@"http://s2.51cto.com/wyfs02/M00/88/A1/wKiom1f9tQnRZeN6AAOOopt2FH4232.png-wh_651x-s_2541885854.png"] options:SDWebImageDownloaderLowPriority progress:nil completed:^(UIImage *image, NSData *data, NSError *error, BOOL finished) {
        NSLog(@" download finish");
    }];
 });
 dispatch_group_notify(group, dispatch_get_main_queue(), ^{
      NSLog(@"main queue");
  });
```

gruop会等到与他绑定的block执行完后再去执行加入到mainqueue的block， 因为下载图片也是异步地，主线程不会等到图片下载完后再去执行，控制台先打印的main queue, 再打印的download finish。这样的话怎么实现图片加载完后再到主线程更新啊。

**Comment by iostalks** [comment]
去了解下 `dispatch_group_notify()`的用法吧。

**Comment by zziazm** [comment]
dispatch_group_notify()会等到queue中的block任务结束后在去执行mainqueue中的任务，但是queue里的block里的加载图片的代码也是异步地，在调用加载图片的方法之后就直接调用dispatch_group_notify函数了，这个时候图片还没加载完，已经开始执行主线程的代码了，这样的话应该不能在主线程里合成图片吧。

**Comment by jhihguan** [comment]
你可能要改用
`dispatch_group_enter(group);`
然後block完成的時候再呼叫
`dispatch_group_leave(group);`

**Comment by cool8jay** [comment]
楼上说得对。

参考。
http://commandshift.co.uk/blog/2014/03/19/using-dispatch-groups-to-wait-for-multiple-web-services/

**Comment by amisare** [comment]
既然dispatch_group_async已经异步了，为什么还要用SDWebImageDownloader，自己把自己绕进去了
