### ISSUE TITLE
关于自定义NSOperation和NSThread所开辟的线程需要创建自动释放池

### ISSUE THREAD

**Issue by tuyaohui** [ChenYilong/iOSInterviewQuestions#68]
我自定义了一个NSOperation，并且复写了main方法，在main方法中用类方法创建了个person。
然后用这个自定义的NSOperation加到queue中去，新开辟了一个线程，发现person是正常被销毁的，并没有内存泄漏。。
NSThread也是一样。

**Comment by ChenYilong** [comment]
加自动释放池是为了autorelease对象, 你的person是autorelease吗?
