### ISSUE TITLE
39题有问题

### ISSUE THREAD

**Issue by liaoshaolim** [ChenYilong/iOSInterviewQuestions#72]
[[NSNotificationCenter defaultCenter] addObserverForName:@"someNotification"
object:nil
queue:[NSOperationQueue mainQueue]
usingBlock:^(NSNotification * notification) {
self.someProperty = xyz; }];

这个也是会引起内存泄漏的，亲测dealloc没有走

**Comment by snlo** [comment]
someProperty强引用了吧

**Comment by ChenYilong** [comment]
已经更正,谢谢指正.
