### ISSUE TITLE
39题关于系统的某些block api的循环引用解释有问题

### ISSUE THREAD

**Issue by agger0207** [ChenYilong/iOSInterviewQuestions#73]
前面有好几个人已经提到了:

	[[NSNotificationCenter defaultCenter] addObserverForName:@"someNotification" 
	                                                  object:nil 
	                           queue:[NSOperationQueue mainQueue]
	                                              usingBlock:^(NSNotification * notification) {
	                                                    self.someProperty = xyz; }]; 

存在内存泄漏；

而下面的代码并不存在内存泄漏:

    dispatch_group_async(self.operationGroup, self.serialQueue, ^{
        [self doSomething];
    });

个人理解：
首先下面这段话是没有问题的

       “所谓“引用循环”是指双向的强引用，所以那些“单向的强引用”（block 强引用 self ）没有问题”

那么为什么第一段NSNotificationCenter的代码会有内存泄漏问题呢？其实和循环引用没有关系；这里block强引用了self, 但是self并没有强引用block; 所以没有循环引用。

这里出现内存泄漏问题实际上是因为，`[NSNoficationCenter defaultCenter]`持有了block, 这个block持有了self; 而`[NSNoficationCenter defaultCenter]`是一个单例，因此这个单例持有了self, 从而导致self不被释放。以下来自API文档：
`The block is copied by the notification center and (the copy) held until the observer registration is removed.`

但整个过程中并没有循环引用，因为self没有持有NotificationCenter, 也没有持有block。即使self持有这个Observer, 并没有任何证据或者文档标明Observer会持有这个block, 所以作者的解释是不正确的。而我个人的理解，这里Observer应该是不持有block的，因为只需要NSNotificationCenter同时持有Observer和block即可实现API所提供的功能, 这里也不存在循环引用。

针对第二段GCD的问题，实际上，self确实持有了queue; 而block也确实持有了self; 但是并没有证据或者文档表明这个queue一定会持有block; 而且即使queue持有了block, 在block执行完毕的时候，由于需要将任务从队列中移除，因此完全可以解除queue对block的持有关系，所以实际上这里也不存在循环引用。下面的测试代码可以验证这一点(其中`HTMemoryDetecter`有一个属性name):

	    HTMemoryDetecter *detector = [[HTMemoryDetecter alloc] init];
    dispatch_group_async(self.operationGroup, self.serialQueue, ^{
        NSLog(@"dispatch_async demoGCDRetainCycle");
        [self.testList addObject:@"demoGCDRetainCycle2"];
        detector.name = @"测试";
        NSLog(@"Detecor 's name: %@", detector.name);
    });
    
那么会看到先打印出`dispatch_async demoGCDRetainCycle`, 然后打印出这个`detecotr`的name, 然后执行`HTMemoryDetecter`的dealloc方法。也就是说在这个block执行完毕的时候，仅由这个block持有的detector就会被释放了, 从而验证这个block都被释放了，即使对应的queue还存在。   

什么时候这里会有循环引用呢？仍然是当self持有block的时候，例如这个block是self的一个strong的属性，但这就和GCD的调用无关了，这个时候无论是否调用GCD的API都会有循环引用的。

**Comment by liftliftlift** [comment]
Good correction！

**Comment by ChenYilong** [comment]
感谢指正, 我修改下答案

**Comment by ChenYilong** [comment]
### 39. 使用系统的某些block api（如UIView的block版本写动画时），是否也考虑引用循环问题？ 


出题只举了一个例子，我们多举几个例子：


 ```Java
//判断如下几种情况,是否有循环引用? 是否有内存泄漏?
//2020-06-01 15:25:46 @iTeaTime(技术清谈)@ChenYilong 

 //情况❶
[UIView animateWithDuration:duration animations:^{ [self.superview layoutIfNeeded]; }]; 

 //情况❷
[[NSNotificationCenter defaultCenter] addObserverForName:@"someNotification" 
                                                  object:nil 
                           queue:[NSOperationQueue mainQueue]
                                              usingBlock:^(NSNotification * notification) {
                                                    self.someProperty = xyz; }]; 

 //情况❸
  _observer = [[NSNotificationCenter defaultCenter] addObserverForName:@"testKey"
                                                                object:nil
                                                                 queue:nil
                                                            usingBlock:^(NSNotification *note) {
      [self dismissModalViewControllerAnimated:YES];
  }];

 //情况❹
    dispatch_group_async(self.operationGroup, self.serialQueue, ^{
        [self doSomething];
    });

//情况❺
[[NSOperationQueue mainQueue] addOperationWithBlock:^{ self.someProperty = xyz; }]; 
 ```

情况一:

系统的某些block api中，比如 `UIView` 的 `block` 版本写动画时不需要考虑循环引用的问题，但也有一些系统 api 需要考虑内存泄漏的问题。

其中 `UIView` 的 `block` 版本写动画时不需要考虑虑循环引用的原因是：

比如典型的代码是这样：

 ```Objective-C
 //@iTeaTime(技术清谈)@ChenYilong 
 //思考：是否有内存泄漏?是否有循环引用?
[UIView animateWithDuration:duration animations:^{ [self.superview layoutIfNeeded]; }]; 
 ```
 
 其中 `block` 会立即执行，所以并不会持有 `block` 。 其中 `duration` 延迟时间并不能决定 `block` 执行的时机， `block` 始终是瞬间执行。
 

 这里涉及了 `CoreAnimation` （核心动画）相关的知识：
 
 首先分清下面几个结构概念：
 
  - UIView 层
  - Layer 层
   - data 数据层
  
  其中
  
  - UIView 层的`block` 仅仅是提供了类似快照 data 的变化。
  - 当真正执行  `Animation` 动画时才会将
“原有状态”与“执行完 `block` 的状态”做一个差值，来去做动画。
 
这个问题关于循环引用的部分已经解答完毕，下面我们来扩展一下，探究一下系统API相关的内存泄漏问题。


-------------

情况二:




 ```Objective-C
 //@iTeaTime(技术清谈)@ChenYilong 
 //思考：是否有内存泄漏?是否有循环引用?
[[NSNotificationCenter defaultCenter] addObserverForName:@"someNotification" 
                                                  object:nil 
                           queue:[NSOperationQueue mainQueue]
                                              usingBlock:^(NSNotification * notification) {
                                                    self.someProperty = xyz; }]; 
 ```
 
 情况三:
 
 ```Objective-C
 //@iTeaTime(技术清谈)@ChenYilong 
 //思考：是否有内存泄漏?是否有循环引用?
  _observer = [[NSNotificationCenter defaultCenter] addObserverForName:@"testKey"
                                                                object:nil
                                                                 queue:nil
                                                            usingBlock:^(NSNotification *note) {
      [self dismissModalViewControllerAnimated:YES];
  }];
 ```
 

情况四:

而下面的代码虽然有类似的结构但并不存在内存泄漏:


 ```Objective-C
 //@iTeaTime(技术清谈)@ChenYilong 
  //思考：是否有内存泄漏?是否有循环引用?
    dispatch_group_async(self.operationGroup, self.serialQueue, ^{
        [self doSomething];
    });
 ```


那么为什么第一段 `NSNotificationCenter` 的代码会有内存泄漏问题呢？


~~我之前的理解: self --> _observer --> block --> self 显然这也是一个循环引用。（对循环引用的成因解释有误，详见issue#73 https://github.com/ChenYilong/iOSInterviewQuestions/issues/73 ）~~


其实和循环引用没有关系；这里 `block` 强引用了 `self` , 但是 `self` 并没有强引用`block`; 所以没有循环引用。

这里出现内存泄漏问题实际上是因为：

 - `[NSNoficationCenter defaultCenter]` 持有了 `block`, 
 - 这个 `block` 持有了 `self`; 
 - 而 `[NSNoficationCenter defaultCenter]` 是一个单例，因此这个单例持有了 `self`, 从而导致 `self` 不被释放。

![https://github.com/ChenYilong](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfcrlp0gn0j30z40lwag6.jpg)

以下来自[APPLE API文档 -- Instance Method
addObserverForName:object:queue:usingBlock:]( https://developer.apple.com/documentation/foundation/nsnotificationcenter/1411723-addobserverforname) ：

> The block is copied by the notification center and (the copy) held until the observer registration is removed.

但整个过程中并没有循环引用，因为 `self` 没有持有 `NotificationCenter` , 也没有持有 `block`。即使 `self` 持有这个`Observer`, 并没有任何证据或者文档标明 `Observer` 会持有这个`block`, 所以我之前的解释是不正确的。这里 Observer 应该是不持有 block 的，因为只需要 `NSNotificationCenter` 同时持有 `Observer` 和 `block` 即可实现 `API` 所提供的功能, 这里也不存在循环引用。

根据上面的原理，思考一下下面的情况：



 ```Objective-C
  //@iTeaTime(技术清谈)@ChenYilong 
  //思考：是否有内存泄漏?是否有循环引用?
[[NSOperationQueue mainQueue] addOperationWithBlock:^{ self.someProperty = xyz; }]; 
 ```
 
 这个因为 `[NSOperationQueue mainQueue]` 并非单例，所以并没有内存泄漏。
 见下图:
 
 ![https://github.com/ChenYilong](https://tva1.sinaimg.cn/large/007S8ZIlgy1gfct4s2979j30y00lq0y0.jpg)
 
-------------

针对第二段 `GCD` 的问题，实际上，self确实持有了queue; 而block也确实持有了self; 但是并没有证据或者文档表明这个queue一定会持有block; 而且即使queue持有了block, 在block执行完毕的时候，由于需要将任务从队列中移除，因此完全可以解除queue对block的持有关系，所以实际上这里也不存在循环引用。下面的测试代码可以验证这一点(其中`CYLUser`有一个属性name):


 ```Objective-C
   //@iTeaTime(技术清谈)@ChenYilong 
	    CYLUser *user = [[CYLUser alloc] init];
    dispatch_group_async(self.operationGroup, self.serialQueue, ^{
        NSLog(@"dispatch_async demoGCDRetainCycle");
        [self.testList addObject:@"demoGCDRetainCycle2"];
        user.name = @"测试";
        NSLog(@"Detecor 's name: %@", detector.name);
    });
 ```

    
那么会看到先打印出 `dispatch_async demoGCDRetainCycle`, 然后打印出这个 `user` 的name, 然后执行 `CYLUser` 的 `-dealloc` 方法。也就是说在这个block执行完毕的时候，仅由这个block持有的 `user`就会被释放了, 从而验证这个 `block` 都被释放了，即使对应的 `queue` 还存在。   


什么时候这里会有循环引用呢？仍然是当 `self` 持有 `block` 的时候，例如这个 `block`是 `self` 的一个 `strong` 的属性，但这就和 `GCD` 的调用无关了，这个时候无论是否调用 `GCD` 的 `API` 都会有循环引用的。


检测代码中是否存在循环引用/内存泄漏问题，可使用 Facebook 开源的一个检测工具  [***FBRetainCycleDetector***](https://github.com/facebook/FBRetainCycleDetector) 。
