### ISSUE TITLE
话说第一个答案不严谨

### ISSUE THREAD

**Issue by lexrus** [ChenYilong/iOSInterviewQuestions#9]
`UserSex` 是啥？Sex 是啥？如果想表达性别的话应该改成:

``` objective-c
typedef NS_ENUM(NSInteger, CYLUserGender) {
    CYLUserGenderUnknown,
    CYLUserGenderMale,
    CYLUserGenderFemale,
    CYLUserGenderNeuter
};
```

**Comment by liuxuan30** [comment]
CYLUserSexMale也可以的。Sex表达性别并无不妥

**Comment by lexrus** [comment]
如果不是做生殖健康 App，应该还是从社会认知上考虑吧。比如某人生理上是女的，但是祂认为自己是男的，或者某人生理上被阉了，但是祂认为自己是女的。另外不想透露性别，或者勇于承认自己是中性人的情况也要考虑。不然默认成男人也不好。

**Comment by zengyun-programmer** [comment]
性别还是用gender比较好吧。。。

**Comment by sauchye** [comment]
gender

**Comment by ibireme** [comment]
sex man, sex woman... 蛤蛤蛤

**Comment by waniwang** [comment]
gender+1

**Comment by ChenYilong** [comment]
已经以【注意】的形式，告知读者这种严谨的做法了 @lexrus

**Comment by dujiepeng** [comment]
深深地震撼了。。。

**Comment by dujiepeng** [comment]
还是认为这个应按照需求来做。

**Comment by MrXiaofengZhang** [comment]
我也是醉了

**Comment by carrotlsp** [comment]
哈哈...想法很棒.

**Comment by Nedoloroso** [comment]
我震惊了！！！   爸爸我只想好好敲代码！

**Comment by kapop** [comment]
简直吓尿了

**Comment by lweisNoN** [comment]
+1...

**Comment by ddrccw** [comment]
强迫症应该是参考fb的gender设置。。

**Comment by SKT-T1-Keyoubi** [comment]
确实更加严谨，虽然平日里都是用sex

**Comment by xiaoniu2014** [comment]
+1...

**Comment by JonyFang** [comment]
选择 gender ...

**Comment by pengwj** [comment]
简直强迫症。

**Comment by jueyingxx** [comment]
该面试了，过来看看

**Comment by qtdc1229** [comment]
gender 党 + 1

**Comment by daiweilai** [comment]
这。。。

**Comment by ALVIN-YANG** [comment]
这么来性别种类就太多了, 还有间歇性的呢 : p

**Comment by devjia** [comment]
@lexrus +1,程序狗就应该这么严谨.

**Comment by WQ-DreamCoder** [comment]
好严谨好细致

**Comment by mooooj** [comment]
蛤蛤

**Comment by litingyan** [comment]
看完，我方了

**Comment by Huang-Libo** [comment]
gender比较严谨，sex偏口语化。

**Comment by Liqiankun** [comment]
在21世纪应该可以严禁了

**Comment by ChenYilong** [comment]
苹果的官方用法： ![5 pic](https://cloud.githubusercontent.com/assets/2911921/14714035/09eee63e-0816-11e6-8d55-94a0d34b1d5b.jpg)

**Comment by dustturtle** [comment]
gender正解啊

**Comment by YingZiDi** [comment]
谈论这些完全没有任何意义，更多的是感觉你在钻牛角尖

**Comment by lovesif** [comment]
膜拜各种强迫症啊 gender正解

**Comment by wilhantian** [comment]
be utterly useless.

**Comment by Sattelizer** [comment]
果然装逼如风....

**Comment by nineteen1** [comment]
我习惯用gender

**Comment by zoloadang** [comment]
gender更严谨正规 +1

**Comment by black-heart** [comment]
gender+1，另外从实际的业务逻辑上想，算上 Unknown 是很有必要的

**Comment by bestyo** [comment]
没有任何意义+1，gender,sex都有性别的意思，爱怎么用怎么用，拿出来说就是装逼了。况且这事代码不是界面，是给程序员看的，你追求的严谨在我看来就是装逼，而且我丝毫不会怀疑有的程序员不认识gender但却知道sex代表性别

**Comment by bestyo** [comment]
没有任何意义+1，gender,sex都有性别的意思，爱怎么用怎么用，拿出来说就是装逼了。况且这是代码不是界面，是给程序员看的，你追求的严谨在我看来就是装逼，而且我丝毫不会怀疑许多程序员不认识gender但却知道sex代表性别。“UserSex是啥？sex是啥？”sex这个词玷污了你作为“严谨人士”的纯洁性吗？我仿佛看到了作为“严谨人士”的你一脸嫌弃的敲下了这几个字

**Comment by bestyo** [comment]
没有任何意义+1，gender,sex都有性别的意思，爱怎么用怎么用。况且这是代码不是界面，是给程序员看的，你追求的严谨在我看来就是装逼，而且我丝毫不会怀疑许多程序员不认识gender但却知道sex代表性别。

**Comment by pandacc** [comment]
gender+1

**Comment by swiftc-org** [comment]
gender + 1

**Comment by 877515063** [comment]
👍

**Comment by jiangliansong19** [comment]
👍 精益求精，gender + 1

**Comment by cuzv** [comment]
我无知我有理，蛤蛤蛤。

**Comment by allpepo** [comment]
gender使用起来更加正式吧...  
sex... 口语还好

**Comment by druidream** [comment]
gender也不是多难的词，为了迁就不认识的程序员而避开这样的词，是智识的倒退。我还是相信一句话：“代码是写给人看的, 顺便能在计算机上运行。”

**Comment by huankong** [comment]
微博观光团，打开。不过还是gender+1

**Comment by huankong** [comment]
微博观光团，打卡。不过还是gender+1

**Comment by callmewhy** [comment]
觉得这种严谨是没有任何意义的人真是可悲，估计也觉得首字母是否大写没有意义吧。。。

就像是该用 登录 的场景错用 登陆 一样，自己感觉没必要纠结太多，在其他人看来已经是无知了

**Comment by engebei** [comment]
sex路过

**Comment by Kojmay** [comment]
哈哈

**Comment by martint028** [comment]
gender 棒棒的

**Comment by PromiscuousYouth** [comment]
哈哈,我也来插一句, `CYLUserGenderNeuter` 改成`CYLUserGenderConfidential`  保密应该会比中性要人性的多吧

**Comment by tianglin** [comment]
后排~表示都用

**Comment by banburytang** [comment]
代码中严谨是好事，世界最终是属于强迫症的。

**Comment by yuhanle** [comment]
感觉 gender 表达会更舒服一些，严谨点儿好，工作性质必须得严谨

**Comment by inkCrazy** [comment]
官方的枚举类型后面为什么要加上数字标记？ @lexrus

**Comment by feihuang89** [comment]
gender还真没用过，不过代码规范还是很有必要的！

**Comment by ZippoLee12138** [comment]
gender👍

**Comment by cuiYuhe** [comment]
想我第一份经过验证的英文简历都是sex.

**Comment by BHAreslee** [comment]
关于用sex还是gender，我觉得有点吹毛求疵了

**Comment by hellolad** [comment]
sex 通用 ，  gender 规范。 支持 gender

**Comment by githhhh** [comment]
歪了、老铁们

**Comment by ZeddShi** [comment]
gender是社会性别有几十种，Facebook的gender option有71种，sex是生理性别只有男 、女 、未知这三种

**Comment by mykoma** [comment]
绝对使用 gender， 程序员绝壁使用 gender

**Comment by peanutli** [comment]
用了gender ,顿时感觉逼格都上来了。提高英语水平的好机会。

**Comment by liwonder** [comment]
最政治正确的方式是 BornGender

**Comment by xiaohuapunk** [comment]
gender 还是 sex ，还有定义几种性别这个应该都需要根据自己产品来考虑吧
gender 口语上，更社会化 
sex 生理上的性别，护照上用的就是 sex
本题应该从语法上来考虑优化，纠结一个单词是不是有点过了。。。

**Comment by lexrus** [comment]
三年了，这个水到掉渣的 issue 浪费了这么多人的碎片时间，我真是罪孽深重。各位还是应该把学习重点放在更有意义的 iOS 底层上，不要像我这样乱发散。

祝好。

**Comment by cavanlee** [comment]
Don't underestimate this interview question，this is the question of Hellobike in 2018.

**Comment by jzliuhuan** [comment]
一如既往的优秀
