### ISSUE TITLE
第34题，autorelease对象的释放时机，对iOS9、10系统不适用

### ISSUE THREAD

**Issue by mws100** [ChenYilong/iOSInterviewQuestions#90]
```
__weak id reference = nil;

- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSString *obj = [NSString stringWithFormat:@"mws"];
    reference = obj;
    NSLog(@"1-%@", reference);
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    NSLog(@"2-%@", reference);
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    NSLog(@"3-%@", reference);
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesBegan:touches withEvent:event];
    NSLog(@"4-%@", reference);
}
```

测试代码如上，在iOS8.4上第3处打印是null，如您所写、也如孙源博客中描述的那样，`viewDidLoad`与`viewWillAppear`两个方法运行在一次runloop迭代中。`viewDidAppear`执行时，上次runloop迭代已经释放了autorelease的obj对象。
但在iOS9.3、iOS10.3上测试时，四处打印均有值。
请问是苹果改变了机制，还是别的原因呢

**Comment by yupliang** [comment]
> 2017-10-25 10:41:49.543963+0800 AA[78411:3940877] 1-mws
2017-10-25 10:41:49.544216+0800 AA[78411:3940877] 2-mws
2017-10-25 10:41:49.547744+0800 AA[78411:3940877] 3-mws
2017-10-25 10:42:02.819713+0800 AA[78411:3940877] 4-mws

测试环境 :模拟器iPhone 6s iOS 11.0.1 ，MRC。
测试代码
`@interface ViewController ()

@property (nonatomic,assign) id reference;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    NSString *obj = [NSString stringWithFormat:@"mws"];
    self.reference = obj;
    NSLog(@"1-%@", self.reference);
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    NSLog(@"2-%@", self.reference);
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    NSLog(@"3-%@", self.reference);
}

- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event {
    [super touchesBegan:touches withEvent:event];
    NSLog(@"4-%@", self.reference);
}
`

@mws10 四处均有值。

**Comment by hssdx** [comment]
@yupliang  你的例子错了，指针成为野指针，地址值不会变化

**Comment by hssdx** [comment]
@mws100  因为那个成了字符串常量，存储在常量区，生命周期是整个 app 运行期间 : )
